from . import edu_student
from . import edu_vaccine
from . import edu_vaccine_type
from . import edu_parent
from . import edu_parent_contact
from . import edu_grade
from . import edu_grade_group
from . import edu_class_type
from . import edu_class_name
